Repository ProjectMeowInc/meowlib.frontend.remaster, pull requests merged in 2024-01, with the labels that each got.

#39 Сделано управление авторами
  src/app/admin/layout.tsx
  src/app/admin/people/[peopleId]/page.tsx
  src/app/admin/people/new/page.tsx
  src/app/admin/people/page.ts
  src/entities/People/PeopleEntity.ts
  src/entities/People/api/PeopleApi.ts
  src/entities/People/models/dto/ILongPeopleDto.ts
  src/entities/People/models/dto/IPeopleDto.ts
  src/entities/People/models/dto/IShortPeopleDto.ts
  src/entities/People/models/requests/ICreatePeopleRequest.ts
  src/entities/People/models/requests/IUpdatePeopleRequest.ts
  src/entities/People/models/responses/ICreatePeopleResponse.ts
  src/entities/People/models/responses/IGetAllPeopleResponse.ts
  src/entities/People/models/responses/IGetPeopleByIdResponse.ts
  src/entities/People/models/responses/IUpdatePeopleResponse.ts
  src/entities/People/services/PeopleService.ts
  src/entities/People/types/PeopleRoleType.ts
  src/pages/admin/MainAdminPage/MainAdminPage.tsx
  src/pages/admin/people/CreatePeoplePage/CreatePeoplePage.tsx
  src/pages/admin/people/CreatePeoplePage/UI/CreatePeopleForm/CreatePeopleForm.tsx
  src/pages/admin/people/CreatePeoplePage/UI/CreatePeopleForm/createPeopleForm.module.css
  src/pages/admin/people/CreatePeoplePage/UI/CreatePeopleForm/useCreatePeopleForm.ts
  src/pages/admin/people/CreatePeoplePage/createPeoplePage.module.css
  src/pages/admin/people/PeopleMainPage/PeopleMainPage.tsx
  src/pages/admin/people/PeopleMainPage/peopleMainPage.module.css
  src/pages/admin/people/PeopleMainPage/usePeopleMainPage.ts
  src/pages/admin/people/UpdatePeoplePage/UI/UpdatePeopleForm/UpdatePeopleForm.tsx
  src/pages/admin/people/UpdatePeoplePage/UI/UpdatePeopleForm/updatePeopleForm.module.css
  src/pages/admin/people/UpdatePeoplePage/UI/UpdatePeopleForm/useUpdatePeopleForm.ts
  src/pages/admin/people/UpdatePeoplePage/UpdatePeoplePage.tsx
  src/pages/admin/people/UpdatePeoplePage/updatePeoplePage.module.css
  src/shared/hooks/useFirstLoading.ts
  src/shared/hooks/useFirstLoadingAsync.ts
  src/shared/hooks/useGetParams.ts
  src/shared/hooks/usePage.ts
Labels: feature

#47 Исправление авто-форматирования кода
  .tools/auto-prettier/AutoPrettier
  .tools/auto-prettier/AutoPrettier.deps.json
  .tools/auto-prettier/AutoPrettier.dll
  .tools/auto-prettier/AutoPrettier.pdb
  .tools/auto-prettier/AutoPrettier.runtimeconfig.json
  .tools/auto-prettier/LibGit2Sharp.dll
  .tools/auto-prettier/runtimes/linux-arm/native/libgit2-a2bde63.so
  .tools/auto-prettier/runtimes/linux-arm64/native/libgit2-a2bde63.so
  .tools/auto-prettier/runtimes/linux-musl-arm/native/libgit2-a2bde63.so
  .tools/auto-prettier/runtimes/linux-musl-arm64/native/libgit2-a2bde63.so
  .tools/auto-prettier/runtimes/linux-musl-x64/native/libgit2-a2bde63.so
  .tools/auto-prettier/runtimes/linux-x64/native/libgit2-a2bde63.so
  .tools/auto-prettier/runtimes/osx-arm64/native/libgit2-a2bde63.dylib
  .tools/auto-prettier/runtimes/osx-x64/native/libgit2-a2bde63.dylib
  .tools/auto-prettier/runtimes/win-arm64/native/git2-a2bde63.dll
  .tools/auto-prettier/runtimes/win-x64/native/git2-a2bde63.dll
  .tools/auto-prettier/runtimes/win-x86/native/git2-a2bde63.dll
  package.json
Labels: feature

#48 Исправление скрипта `style-fix` под Windows
  .tools/auto-prettier/AutoPrettier.dll
  .tools/auto-prettier/AutoPrettier.pdb
  package.json
Labels: bug

#49 Хуки перенесены к компонентам
  src/entities/Auth/models/dto/SignInDto.ts
  src/entities/BookComments/models/dto/ICommentDto.ts
  src/entities/User/api/UsersApi.ts
  src/entities/User/models/UserEntity.ts
  src/entities/User/models/dto/IUpdateUserDTO.ts
  src/entities/User/models/dto/IUserDTO.ts
  src/entities/User/models/requests/IUpdateUserByIdRequest.ts
  src/entities/User/models/response/IGetAllUsersResponse.ts
  src/entities/User/models/response/IGetUserByIdResponse.ts
  src/entities/User/models/response/IUpdateUserByIdResponse.ts
  src/entities/User/service/UsersService.ts
  src/entities/Users/models/UserEntity.ts
  src/pages/AuthPage/UI/AuthorizationForm/AuthorizationForm.tsx
  src/pages/AuthPage/UI/AuthorizationForm/useAuthorizationForm.ts
  src/pages/AuthPage/UI/NavAuth/NavAuth.tsx
  src/pages/AuthPage/UI/NavAuth/useNavAuth.ts
  src/pages/AuthPage/UI/RegistrationForm/RegistrationForm.tsx
  src/pages/AuthPage/UI/RegistrationForm/useRegistrationForm.ts
  src/pages/admin/users/MainUsersPage/MainUsersPage.tsx
  src/pages/admin/users/UI/UpdateUserForm/UpdateUserForm.tsx
  src/pages/admin/users/UI/UpdateUserForm/useUpdateUserForm.ts
  src/pages/admin/users/UI/UserItem/UserItem.tsx
  src/pages/admin/users/UpdateUserPage/UpdateUserPage.tsx
Labels: refactoring

#50 Добавление линтера
  .tools/auto-prettier/AutoPrettier.dll
  .tools/auto-prettier/AutoPrettier.pdb
  package.json
Labels: feature

#51 Сделана страница FAQ
  src/app/(withMenu)/rules/page.tsx
  src/app/globals.css
  src/pages/MainPage/UI/Menu/Menu.tsx
  src/pages/RulesPage/RulesPage.tsx
  src/pages/RulesPage/UI/RuleItem/RuleItem.tsx
  src/pages/RulesPage/UI/RuleItem/ruleItem.module.css
  src/pages/RulesPage/rulesPage.module.css
  src/shared/Layout/Layout.module.css
  src/shared/Layout/Layout.tsx
Labels: feature

#53 Замена `useEffect` на `useFirstLoading`
  src/pages/BookPages/BookPage/UI/CommentList/useCommentList.ts
  src/pages/admin/users/MainUsersPage/MainUsersPage.tsx
Labels: refactoring

#56 Добавлено обновление авторизации
  package-lock.json
  package.json
  src/entities/Auth/models/dto/AccessTokenData.ts
  src/entities/Auth/models/dto/AccessTokenDto.ts
  src/entities/Auth/service/AuthService.ts
  src/pages/AuthPage/UI/AuthorizationForm/useAuthorizationForm.ts
  src/pages/AuthPage/UI/RegistrationForm/useRegistrationForm.ts
  src/shared/services/HTTPResult/HTTPResult.ts
  src/shared/services/TokenService.ts
Labels: feature

#57 `HTTPResult` переименован в `HTTPRequest`
  src/entities/Auth/api/AuthorizationApi.ts
  src/entities/Book/api/BookApi.ts
  src/entities/People/api/PeopleApi.ts
  src/entities/Tag/api/TagApi.ts
  src/entities/User/api/UsersApi.ts
  src/shared/services/HTTPResult/HTTPRequest.ts
Labels: refactoring

#58 Создана возможность добавление книги в избранное
  public/img/icons/chevron-down.png
  src/entities/UserFavorite/UserBookStatuses.ts
  src/entities/UserFavorite/api/UserFavoriteApi.ts
  src/entities/UserFavorite/models/dto/IUserFavoriteBook.ts
  src/entities/UserFavorite/models/dto/IUserFavoritesList.ts
  src/entities/UserFavorite/models/requests/IAddBookInFavoriteRequest.ts
  src/entities/UserFavorite/models/responses/IGetAllBooksInFavoriteResponse.ts
  src/entities/UserFavorite/models/responses/IGetBookInFavoriteByIdResponse.ts
  src/entities/UserFavorite/service/UserFavoriteService.ts
  src/pages/BookPages/BookPage/BookPage.tsx
  src/pages/BookPages/BookPage/UI/BookImage/BookImage.tsx
  src/pages/BookPages/BookPage/UI/BookImage/bookImage.module.css
  src/pages/BookPages/BookPage/UI/SelectStatusButton/SelectStatusButton.tsx
  src/pages/BookPages/BookPage/UI/SelectStatusButton/selectStatusButton.module.css
  src/pages/BookPages/BookPage/UI/SelectStatusButton/useSelectStatusButton.ts
  src/pages/admin/books/MainBooksPage/MainBooksPage.tsx
  src/pages/admin/books/MainBooksPage/UI/BookItem/BookItem.module.css
  src/pages/admin/books/MainUpdateBookPage/MainUpdateBookPage.module.css
  src/pages/admin/books/UpdateBookPeopleForm/UI/AddPeopleItem/AddPeopleItem.module.css
  src/pages/admin/books/UpdateBookPeopleForm/UI/DeleteBookPeopleItem/DeleteBookPeopleItem.module.css
  src/pages/admin/books/UpdateBookPeopleForm/UpdateBookPeopleForm.module.css
  src/pages/admin/books/UpdateBookTagsForm/UI/AddTagListItem/AddTagListItem.module.css
  src/pages/admin/books/UpdateBookTagsForm/UI/DeleteTagListItem/DeleteTagListItem.module.css
  src/pages/admin/books/UpdateBookTagsForm/UpdateBookTagsForm.module.css
  src/shared/UI/BurgerMenu/useBurgerMenu.ts
  src/shared/UI/button/Button.tsx
  src/shared/services/RedirectService.ts
  src/shared/services/TokenService.ts
Labels: feature

#64 Добавлена проверка ESLint
  .github/workflows/eslint.yml
Labels: github

#66 Create dependabot.yml
  .github/dependabot.yml
Labels: feature, github
